package project.ui;

import project.service.ChangeSpeed;
import project.service.ChangeTemperature;
import javax.swing.ImageIcon;

/**
 *
 * @author MyPC
 */
public class AirConditional extends javax.swing.JFrame {

	/**
	 * Creates new form AirConditional1
	 */
	public AirConditional() {
		initComponents();
		ClassLoader classLoader = getClass().getClassLoader();
		setIconImage(new ImageIcon(classLoader.getResource("icon/air_conditional.png")).getImage());
		setTitle("AirConditional");
		setResizable(false);
		setLocation(0, 0);
		airTempLabel.setText(Unit.temperatureLabel + ":");
		airTempIndexLabel.setText(ChangeTemperature.MIN_TEMP + Unit.tempUnit);
		airSpeedLabel.setText(Unit.speedLabel + ":");
		airSpeedIndexLabel.setText(ChangeSpeed.MIN_SPEED + Unit.speedUnit);
		airDirectionLabel.setText(Unit.directionLabel + ":");
		airDirectionIndexLabel.setText("Middle");
	}

	// Interface change UI
	void setAirStatusIndexLabel(boolean value) {
		if (value == true) {
			airStateIndexLabel.setText("ON");
		} else
			airStateIndexLabel.setText("OFF");
	}

	void setAirTempIndexLabel(int value) {
		airTempIndexLabel.setText(value + Unit.tempUnit);
	}

	void setAirSpeedIndexLabel(int value) {
		airSpeedIndexLabel.setText(value + Unit.speedUnit);
	}

	void setAirDirectionIndexLabel(int value) {
		String direction;
		if (value > 10)
			direction = "Right";
		else if (value < -10)
			direction = "Left";
		else
			direction = "Middle";
		airDirectionIndexLabel.setText(direction);
	}

	public javax.swing.JLabel getAirTempIndexLabel() {
		return airTempIndexLabel;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		airStateLabel = new javax.swing.JLabel();
		airDirectionIndexLabel = new javax.swing.JLabel();
		airDirectionLabel = new javax.swing.JLabel();
		airSpeedLabel = new javax.swing.JLabel();
		airSpeedIndexLabel = new javax.swing.JLabel();
		airTempLabel = new javax.swing.JLabel();
		airTempIndexLabel = new javax.swing.JLabel();
		airStateIndexLabel = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Air Conditional");

		airStateLabel.setText("Status");

		airDirectionIndexLabel.setText("Left");

		airDirectionLabel.setText("Wind Conditional:");

		airSpeedLabel.setText("Speed:");

		airSpeedIndexLabel.setText("30km/h");

		airTempLabel.setText("Temperature:");

		airTempIndexLabel.setText("27℃");

		airStateIndexLabel.setText("OFF");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(70, 70, 70)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(airDirectionLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(airSpeedLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(airTempLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(airStateLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGap(26, 26, 26)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(airTempIndexLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(airSpeedIndexLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(airDirectionIndexLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 151,
												Short.MAX_VALUE)
										.addComponent(airStateIndexLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addGroup(layout.createSequentialGroup().addGap(162, 162, 162).addComponent(jLabel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(69, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(airStateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(airStateIndexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(31, 31, 31)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(airTempLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(airTempIndexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(37, 37, 37)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(airSpeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(airSpeedIndexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(35, 35, 35)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(airDirectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(airDirectionIndexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(67, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel airDirectionIndexLabel;
	private javax.swing.JLabel airDirectionLabel;
	private javax.swing.JLabel airSpeedIndexLabel;
	private javax.swing.JLabel airSpeedLabel;
	private javax.swing.JLabel airStateIndexLabel;
	private javax.swing.JLabel airStateLabel;
	private javax.swing.JLabel airTempIndexLabel;
	private javax.swing.JLabel airTempLabel;
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables
}
