/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.ui;

import javax.swing.ImageIcon;

/**
 *
 * @author MyPC
 */
public class Light extends javax.swing.JFrame {

	/**
	 * Creates new form Light
	 */
	public Light() {
		initComponents();
		ClassLoader classLoader = getClass().getClassLoader();
		setIconImage(new ImageIcon(classLoader.getResource("icon/air_conditional.png")).getImage());
		setTitle("Light");
		setResizable(false);
		onStatus.setSelected(true);
		setLocation(600, 200);
	}

	void setLightStatus(boolean value) {
		if (value == false) {
			offStatus.setSelected(true);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		onStatus = new javax.swing.JRadioButton();
		offStatus = new javax.swing.JRadioButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Light");

		jLabel2.setText("Status");

		buttonGroup1.add(onStatus);
		onStatus.setText("ON");
		onStatus.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onStatusActionPerformed(evt);
			}
		});

		buttonGroup1.add(offStatus);
		offStatus.setText("OFF");
		offStatus.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				offStatusActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup().addGap(156, 156, 156).addComponent(jLabel1))
								.addGroup(layout.createSequentialGroup().addGap(60, 60, 60).addComponent(jLabel2)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65,
												Short.MAX_VALUE)
										.addComponent(onStatus)))
						.addGap(56, 56, 56).addComponent(offStatus).addContainerGap(102, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel1).addGap(96, 96, 96)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(onStatus).addComponent(offStatus))
						.addContainerGap(156, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void offStatusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_offStatusActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_offStatusActionPerformed

	private void onStatusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onStatusActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_onStatusActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JRadioButton offStatus;
	private javax.swing.JRadioButton onStatus;
	// End of variables declaration//GEN-END:variables
}
